default:
  genome_version: "hg19"
  app_prod: no
  cache_directory: default
  db_path: "app/data/testdata"
  prefix: "test"
  app_title: "My App"


production:
  genome_version: "hg19"
  app_prod: no
  cache_directory: default
  db_path: "app/data/testdata"
  prefix: "test"
  app_title: "My App"


demo:
  genome_version: "hg19"
  app_prod: no
  cache_directory: default
  db_path: "app/data/testdata"
  prefix: "test"
  app_title: "My App"


