# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(ComplexHeatmap)
library(dplyr)
library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
library(IlluminaHumanMethylation450kmanifest)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(IlluminaHumanMethylationEPICmanifest)
library(minfi)
library(rhino)
library(Rtsne)
library(shinybusy)
library(shinytest2)
library(shinyvalidate)
library(treesitter)
library(treesitter.r)
